library(proxy)
#View(user_item)
user_item_t <- t(user_item)
user_similarity <- as.matrix(dist(user_item_t, method = "pearson"))
user_similarity <- as.matrix(dist(user_item_t, method = "cosine"))
user_similarity <- as.matrix(dist(user_item_t, method = "euclidean"))
item_similarity <- as.matrix(dist(user_item, method = "pearson"))
item_similarity <- as.matrix(dist(user_item, method = "cosine"))
item_similarity <- as.matrix(dist(user_item, method = "euclidean"))
#View(user_similarity)
#View(item_similarity)